version: "2"

linters:
  default: none
  enable:
    - errcheck
    - govet
    - revive
    - gosec
    - goconst
    - gocritic
    - staticcheck
    - ineffassign
    - unused
    - misspell
  settings:
    misspell:
      ignore-rules:
        - routeros
  exclusions:
    presets:
      - std-error-handling

formatters:
  enable:
    - gofmt
    - goimports

issues:
  max-issues-per-linter: 50
  max-same-issues: 3